name: e_commerce_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.0.5
  image_picker: ^1.1.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  http: ^1.2.1
  animated_text_kit: ^4.2.3
  animations: ^2.0.11
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  flutter_local_notifications: ^17.1.2
  google_generative_ai: ^0.4.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  uuid: ^4.4.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#6C63FF"
  image: assets/images/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/DeveloperAadi/aditya.png
    - assets/images/logo.png